import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";
import React from "react";
import "react-loading-skeleton/dist/skeleton.css";
import MainLayout from "@/components/MainLayout";

const epilogue = Epilogue({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <MainLayout>
          <div className="py-4">{children}</div>
        </MainLayout>
      </body>
    </html>
  );
}
